### ISSUE TITLE
Cannot find module pm2-webshell/package.json

### ISSUE THREAD

**Issue by inickel** [pm2-hive/pm2-webshell#9]
when i try install in cli:pm2 install pm2-webshell
stack below 

Error: Cannot find module '/Users/Nickel/.pm2/node_modules/pm2-webshell/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at startModule (/usr/local/lib/node_modules/pm2/lib/Modularizer.js:40:22)
    at /usr/local/lib/node_modules/pm2/lib/Modularizer.js:151:9
    at /usr/local/lib/node_modules/pm2/lib/Configuration.js:103:14
    at FSReqWrap.oncomplete (fs.js:82:15)

any idear?
btw platform in MAC
node v5.0.0
npm v3.3.6

**Comment by rudders** [comment]
same issue here. does not seem to install to the correct directory

**Comment by JNK** [comment]
Also have this issue, i'll try to figure out what is going on as I am interested to see it working...

**Comment by JNK** [comment]
Submitted pull-request with fix 👍 - in the meantime you (@inickel, @rudders) can try with `pm2 install pm2-webshell-jnk`
When I installed on vagrant ubuntu/trusty64 I also had to run `apt-get install libpam0g-dev`because some headers were missing. Also tested on OS X 10.11.1 where it worked without any other extra packages. Let me know if it works for you.

**Comment by rudders** [comment]
Nicene - works great - thanks (on RASPIAN JESSY btw)

**Comment by Unitech** [comment]
I have to upgrade the tty.js version, installation fails because the modified tty.js in pm2-webshell is not compatible with node 4+

**Comment by Unitech** [comment]
Thanks JNK for the PR! pm2-webshell updated/published
